name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: sona-windows
          path: build/windows/x64/runner/Release
